name       : lazygit
version    : 0.27.2
release    : 9
source     :
    - https://github.com/jesseduffield/lazygit/archive/refs/tags/v0.27.2.tar.gz : 0e3322540095cd4fbde546f23bf89c7db288800cc4a142a8dbcb1d34b31b7a15
license    : MIT
homepage   : https://github.com/jesseduffield/lazygit
component  : programming.tools
summary    : A simple terminal UI for git commands, written in Go with the gocui library.
description: |
    A simple terminal UI for git commands, written in Go with the gocui library.
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o lazygit

install    : |
    install -Dm00755 $workdir/lazygit $installdir/usr/bin/lazygit
