name       : lazygit
version    : 0.24.2
release    : 6
source     :
    - https://github.com/jesseduffield/lazygit/archive/v0.24.2.tar.gz : 95f629d57b459a3414af0582c20835edc970ec83a2c791cff97e5b8aac3b7025
license    : MIT
component  : programming.tools
summary    : A simple terminal UI for git commands, written in Go with the gocui library.
description: |
    A simple terminal UI for git commands, written in Go with the gocui library.
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o lazygit

install    : |
    install -Dm00755 $workdir/lazygit $installdir/usr/bin/lazygit
