name       : lazygit
version    : 0.23.2
release    : 4
source     :
    - https://github.com/jesseduffield/lazygit/archive/v0.23.2.tar.gz : a541756a28d00ffc1fc9ba385c06b91fcc51df815a2919f7072873c969b2034c
license    : MIT
component  : programming.tools
summary    : A simple terminal UI for git commands, written in Go with the gocui library.
description: |
    A simple terminal UI for git commands, written in Go with the gocui library.
networking : yes
builddeps  :
    - golang
    - go-md2man
build      : |
    go build -ldflags "-X main.version=$version" -o lazygit

    # Make a man page
    go-md2man -in README.md -out lazygit.1
install    : |
    install -Dm00755 $workdir/lazygit $installdir/usr/bin/lazygit
    install -Dm00644 $workdir/lazygit.1 $installdir/usr/man/man1/lazygit.1
