name       : lazygit
version    : 0.28.1
release    : 11
source     :
    - https://github.com/jesseduffield/lazygit/archive/refs/tags/v0.28.1.tar.gz : 56daf4fd751f5ce5703974aa2f0d6c4b77f20225c9ed639a61633033c87704c0
license    : MIT
homepage   : https://github.com/jesseduffield/lazygit
component  : programming.tools
summary    : A simple terminal UI for git commands, written in Go with the gocui library.
description: |
    A simple terminal UI for git commands, written in Go with the gocui library.
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o lazygit

install    : |
    install -Dm00755 $workdir/lazygit $installdir/usr/bin/lazygit
