name       : lazygit
version    : 0.32.2
release    : 18
source     :
    - https://github.com/jesseduffield/lazygit/archive/refs/tags/v0.32.2.tar.gz : 44a735c4ee78838dc918e82bd5070b154600cd24992259fd698f2116a797012b
license    : MIT
homepage   : https://github.com/jesseduffield/lazygit
component  : programming.tools
summary    : A simple terminal UI for git commands, written in Go with the gocui library.
description: |
    A simple terminal UI for git commands, written in Go with the gocui library.
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o lazygit

install    : |
    install -Dm00755 $workdir/lazygit $installdir/usr/bin/lazygit
