name       : lazygit
version    : 0.40.2
release    : 26
source     :
    - https://github.com/jesseduffield/lazygit/archive/refs/tags/v0.40.2.tar.gz : 146bd63995fcf2f2373bbc2143b3565b7a2be49a1d4e385496265ac0f69e4128
license    : MIT
homepage   : https://github.com/jesseduffield/lazygit
component  : programming.tools
summary    : A simple terminal UI for git commands, written in Go with the gocui library.
description: |
    A simple terminal UI for git commands, written in Go with the gocui library.
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o lazygit

install    : |
    install -Dm00755 $workdir/lazygit $installdir/usr/bin/lazygit
