name       : lazygit
version    : 0.37.0
release    : 22
source     :
    - https://github.com/jesseduffield/lazygit/archive/refs/tags/v0.37.0.tar.gz : 8545f3cffe110de80c88859cd11b42eaccb71f4c239c5bc2bff841f623438296
license    : MIT
homepage   : https://github.com/jesseduffield/lazygit
component  : programming.tools
summary    : A simple terminal UI for git commands, written in Go with the gocui library.
description: |
    A simple terminal UI for git commands, written in Go with the gocui library.
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o lazygit

install    : |
    install -Dm00755 $workdir/lazygit $installdir/usr/bin/lazygit
