name       : lazygit
version    : 0.28.2
release    : 13
source     :
    - https://github.com/jesseduffield/lazygit/archive/refs/tags/v0.28.2.tar.gz : 4925089bff0fee55ccc495fdcc2d396e48e04d16ad8d6681b6cce7b10eefa2b4
license    : MIT
homepage   : https://github.com/jesseduffield/lazygit
component  : programming.tools
summary    : A simple terminal UI for git commands, written in Go with the gocui library.
description: |
    A simple terminal UI for git commands, written in Go with the gocui library.
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o lazygit

install    : |
    install -Dm00755 $workdir/lazygit $installdir/usr/bin/lazygit
