name       : lazygit
version    : 0.38.2
release    : 23
source     :
    - https://github.com/jesseduffield/lazygit/archive/refs/tags/v0.38.2.tar.gz : 2e727db952022c0518443d18c9b8a97a882970b93c5ab198ff33bb8ed2166c2f
license    : MIT
homepage   : https://github.com/jesseduffield/lazygit
component  : programming.tools
summary    : A simple terminal UI for git commands, written in Go with the gocui library.
description: |
    A simple terminal UI for git commands, written in Go with the gocui library.
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o lazygit

install    : |
    install -Dm00755 $workdir/lazygit $installdir/usr/bin/lazygit
