name       : lazygit
version    : '0.29'
release    : 14
source     :
    - https://github.com/jesseduffield/lazygit/archive/refs/tags/v0.29.tar.gz : f25de2ddab99d2ea06aae87e0be6365033b2ceb8efe94807c8b074884d5e8e38
license    : MIT
homepage   : https://github.com/jesseduffield/lazygit
component  : programming.tools
summary    : A simple terminal UI for git commands, written in Go with the gocui library.
description: |
    A simple terminal UI for git commands, written in Go with the gocui library.
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o lazygit

install    : |
    install -Dm00755 $workdir/lazygit $installdir/usr/bin/lazygit
